"""Public JSON-compatible return types. Generated by tools/generate_models.py.

These are ordinary dicts/lists at runtime, with TypedDict keys for autocomplete
and static checking. Optional keys use NotRequired; explicit null uses None.
They are type declarations, not a runtime validation or deserialization layer.
"""

from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict, Union

JSONValue: TypeAlias = Union[None, bool, int, float, str, list["JSONValue"], dict[str, "JSONValue"]]


class Error(TypedDict):
    "JSON response fields for Error."

    error: str
    message: NotRequired[str]
    code: NotRequired[str]
    upstream_status: NotRequired[int]


Context: TypeAlias = dict[str, str]


class Link(TypedDict):
    "JSON response fields for Link."

    title: str
    url: str


class Status(TypedDict):
    "JSON response fields for Status."

    authenticated: Literal[True]
    course_count: int
    context: Context
    browser_required: Literal[False]


class Course(TypedDict):
    "JSON response fields for Course."

    code: str
    title: str
    course_id: int
    source_url: NotRequired[str]
    text: NotRequired[str]
    faculty: NotRequired[str]
    semester: NotRequired[str]
    catalog_url: NotRequired[str]
    credits: NotRequired[int | None]
    completion: NotRequired[str | None]
    grade: NotRequired[str | None]
    teachers: NotRequired[list[str]]
    seminar: NotRequired[str | None]
    forums: NotRequired[list[CourseForumsItem]]
    ropot_url: NotRequired[str | None]
    syllabus_entry_url: NotRequired[str | None]
    reservation_urls: NotRequired[list[str]]
    materials_url: NotRequired[str | None]


class CourseForumsItem(TypedDict):
    "JSON response fields for CourseForumsItem."

    title: str
    url: str
    forum_id: str | None


class FileVariant(TypedDict):
    "JSON response fields for FileVariant."

    object_id: str | None
    name: str | None
    path: str | None
    mime_type: str | None
    size: int | None
    uploaded: str | None


class FileNode(TypedDict):
    "JSON response fields for FileNode."

    node_id: str
    title: str
    path: str | None
    parent_id: str | None
    modified: str | None
    child_count: int
    object_count: int
    state: Literal["objects_listed", "children_listed", "metadata_only"]
    variants: list[FileVariant]
    uploaded_by: NotRequired[str | None]
    description: NotRequired[str]


class Files(TypedDict):
    "JSON response fields for Files."

    course: str
    source_url: str
    format: Literal["native_xml"]
    nodes: list[FileNode]
    node_count: int
    variant_count: int


class FileRead(TypedDict):
    "JSON response fields for FileRead."

    course: str
    path: str
    mime_type: str
    bytes: int
    sha256: str
    source_url: str
    text: NotRequired[str]
    saved_to: NotRequired[str]


class SyllabusSection(TypedDict):
    "JSON response fields for SyllabusSection."

    title: str
    id: str | None
    schedule_text: str
    state: Literal["available", "locked"]
    text: str


class Syllabus(TypedDict):
    "state=not_exposed is returned only when no syllabus entry was discovered. Otherwise text and source fields are included."

    course: str
    state: NotRequired[Literal["not_exposed"]]
    title: NotRequired[str]
    sections: list[SyllabusSection]
    text: NotRequired[str]
    links: NotRequired[list[Link]]
    source_url: NotRequired[str]
    content_hash: NotRequired[str]


class Availability(TypedDict):
    "JSON response fields for Availability."

    opens: str | None
    closes: str | None
    text: str


class Ropot(TypedDict):
    "JSON response fields for Ropot."

    title: str
    qref_path: str | None
    url: str
    availability: list[Availability]
    status_text: str
    grading_text: str
    attempt_started_by_client: Literal[False]


class Ropots(TypedDict):
    "JSON response fields for Ropots."

    course: str
    items: list[Ropot]
    count: int
    state: Literal["listed", "empty", "suppressed"]
    source_url: str


class ForumPost(TypedDict):
    "JSON response fields for ForumPost."

    id: str
    title: str
    author: str
    date_text: str
    text: str
    links: list[Link]
    url: str
    content_hash: str


class Forum(TypedDict):
    "JSON response fields for Forum."

    forum_id: str
    title: NotRequired[str]
    state: Literal["listed", "stale_semester"]
    source_url: str
    posts: list[ForumPost]
    pages_read: NotRequired[int]
    pagination_incomplete: NotRequired[bool]


class Forums(TypedDict):
    "JSON response fields for Forums."

    course: str
    forums: list[Forum]
    post_count: int


class Reservation(TypedDict):
    "JSON response fields for Reservation."

    id: str
    event: str
    starts_at: str | None
    registered: bool | None
    registration_status_text: str
    occupied: int | None
    capacity: int | None
    registration_opens: str | None
    registration_closes_date: str | None
    closing_date_inclusive: bool
    text: str


class ReservationSeries(TypedDict):
    "JSON response fields for ReservationSeries."

    source_url: str
    items: list[Reservation]
    text: str
    series_id: str | None


class Reservations(TypedDict):
    "JSON response fields for Reservations."

    course: str
    series: list[ReservationSeries]
    state: Literal["listed", "not_exposed"]


class Notes(TypedDict):
    "JSON response fields for Notes."

    source_url: str
    text: str


class SnapshotError(TypedDict):
    "JSON response fields for SnapshotError."

    course: NotRequired[str]
    resource: str
    error: str
    code: NotRequired[str]


class CourseResources(TypedDict):
    "JSON response fields for CourseResources."

    syllabus: NotRequired[Syllabus]
    ropots: NotRequired[Ropots]
    forums: NotRequired[Forums]
    reservations: NotRequired[Reservations]
    files: NotRequired[Files]


class Snapshot(TypedDict):
    "A sequential observation. Inspect complete and errors; true does not imply every document body was read or every task inferred."

    schema_version: Literal[1]
    captured_at: str
    context: Context
    courses: list[Course]
    requested_resources: list[str]
    data: dict[str, CourseResources]
    notes: NotRequired[Notes]
    errors: list[SnapshotError]
    complete: bool


class OpenSubmission(TypedDict):
    "JSON response fields for OpenSubmission."

    title: str
    path: str
    faculty: str
    semester: str
    course: str
    open_for_submission: Literal[True]
    source_url: str
    context_text: str


class OpenSubmissions(TypedDict):
    "JSON response fields for OpenSubmissions."

    source_url: str
    items: list[OpenSubmission]
    count: int
    state: Literal["listed", "empty"]
    scope: Literal["open_to_current_user"]
    text: str


class SubmissionCandidate(TypedDict):
    "JSON response fields for SubmissionCandidate."

    title: str
    path: str
    node_id: str | None
    source_url: str
    open_for_submission: bool | None
    submission_status: Literal["unknown"]


class Submissions(TypedDict):
    "JSON response fields for Submissions."

    course: str
    source_url: str
    items: list[SubmissionCandidate]
    count: int
    scope: Literal["visible_folders_and_open_boxes"]
    state: Literal["listed", "empty"]
    open_index_url: str


class SubmissionFolder(TypedDict):
    "JSON response fields for SubmissionFolder."

    path: str
    title: str
    description: str
    is_folder: bool
    submission_box_code: str | None
    can_read: bool
    can_insert: bool
    permissions: dict[str, JSONValue]
    attributes: dict[str, JSONValue]
    inherited_attributes: dict[str, JSONValue]
    modified_raw: str | None
    source_url: str


class SubmissionBox(TypedDict):
    "Permissions and visible files only. own_files_visible is positive uploader evidence, not a successful or graded submission. Empty/insert-only views remain unknown."

    course: str
    source_url: str
    path: str
    folder: SubmissionFolder
    children: list[SubmissionFolder]
    visibility: Literal["readable", "insert_only", "metadata_only"]
    submission_status: Literal["unknown", "own_files_visible"]
    scope: Literal["visible_children"]
    text: str
    visible_files: list[FileNode]
    own_files: list[FileNode]


class CalendarEvent(TypedDict):
    "JSON response fields for CalendarEvent."

    id: str
    provider_id: str | None
    type_code: str
    kind: Literal[
        "notice",
        "exam_registration",
        "exam",
        "ropot",
        "semester",
        "holiday",
        "timetable",
        "online_teaching",
        "unknown",
    ]
    title: str
    start: str
    end: str | None
    all_day: bool
    location: str | None
    description: str | None
    url: str | None
    hidden_in_ui: bool
    boundary_code: str | None


class Calendar(TypedDict):
    "Events supplied by IS, potentially across multiple semesters. Date filters are local, start-inclusive/end-exclusive. Includes hidden layers. Source coverage dates do not guarantee completeness."

    source_url: str
    timezone: Literal["Europe/Prague"]
    items: list[CalendarEvent]
    count: int
    upstream_event_count: int
    layers: list[CalendarLayersItem]
    hidden_type_codes: list[str]
    scope: Literal["events_exposed_by_IS"]
    coverage_start: str | None
    coverage_end: str | None
    range_completeness: Literal["not_guaranteed"]
    requested_start: str | None
    requested_end: str | None
    requested_kinds: list[str] | None


class CalendarLayersItem(TypedDict):
    "JSON response fields for CalendarLayersItem."

    title: str
    type_codes: list[str]


class TimetableEntry(TypedDict):
    "JSON response fields for TimetableEntry."

    course_label: str
    title: str
    weekday: int | None
    start_time: str | None
    end_time: str | None
    kind: Literal["lecture", "other"]
    location: str | None
    schedule_text: str
    exceptions_text: str | None
    detail_text: str
    url: str | None


class Timetable(TypedDict):
    "JSON response fields for Timetable."

    source_url: str
    timezone: Literal["Europe/Prague"]
    items: list[TimetableEntry]
    count: int
    scope: Literal["weekly_pattern"]
    text: str


class ExamSeries(TypedDict):
    "JSON response fields for ExamSeries."

    course_id: str
    series_id: str | None
    title: str
    kind: Literal["teaching_reservation", "exam_or_other"]
    source_url: str
    items: list[Reservation]
    text: str


class Exams(TypedDict):
    "JSON response fields for Exams."

    source_url: str
    series: list[ExamSeries]
    registered_items: list[Reservation]
    text: str
    series_count: int
    pagination_incomplete: bool
    errors: list[ExamsErrorsItem]
    complete: bool


class ExamsErrorsItem(TypedDict):
    "JSON response fields for ExamsErrorsItem."

    course_id: str
    series_id: str | None
    error: str
    code: NotRequired[str]


class MailFolder(TypedDict):
    "JSON response fields for MailFolder."

    id: str
    name: str
    type: str | None
    unread_count: int | None
    total_count: int | None


class MailFolders(TypedDict):
    "JSON response fields for MailFolders."

    source_url: str
    items: list[MailFolder]
    count: int
    forwarding_enabled: bool


class MailSummary(TypedDict):
    "JSON response fields for MailSummary."

    id: str
    subject: str
    sender_name: str
    sender_address: str | None
    date_text: str
    size_text: str
    flags: str
    unread: bool
    url: str
    folder_id: str | None


class MailListing(TypedDict):
    "Locally paged native header table. Upstream start/count are not relied upon. Upstream truncation remains explicit and does not invent a next page."

    source_url: str
    folders: list[MailFolder]
    items: list[MailSummary]
    count: int
    folder_id: str | None
    total_count: int | None
    forwarding_enabled: bool
    start: int
    limit: int
    next_start: int | None
    pagination_incomplete: bool
    pagination_mode: Literal["local"]
    upstream_returned_count: int
    upstream_truncated: bool


class MailBody(TypedDict):
    "JSON response fields for MailBody."

    part_id: str
    mime_type: Literal["text/plain", "text/html"]
    text: str


class MailAttachment(TypedDict):
    "JSON response fields for MailAttachment."

    part_id: str
    filename: str | None
    mime_type: str
    bytes: int
    sha256: str


class MailMessage(TypedDict):
    "Native RFC822 export parsed into MIME parts. Export marks unread mail read, so explicit allow_mark_read=true is required. HTML is untrusted text."

    id: str
    source_url: str
    headers: dict[str, list[str]]
    bodies: list[MailBody]
    attachments: list[MailAttachment]
    read_state_may_change: Literal[True]


class NoticeCard(TypedDict):
    "JSON response fields for NoticeCard."

    id: str
    title: str
    url: str
    author: str
    date_text: str
    date_detail: str
    unread: bool
    priority: Literal["important", "targeted", "normal"]
    preview: str | None


class Notices(TypedDict):
    "Cards only. Overview is curated, not all notices. Full body route requires explicit read-state opt-in."

    source_url: str
    items: list[NoticeCard]
    count: int
    pages_read: int
    pagination_incomplete: bool
    scope: Literal["overview", "board"]
    board_links: list[Link]


class NoticeDetail(TypedDict):
    "JSON response fields for NoticeDetail."

    id: str
    source_url: str
    title: str
    author: str
    date_text: str
    text: str
    links: list[Link]
    content_hash: str
    read_state_may_change: Literal[True]


class LoginResult(TypedDict):
    "JSON response fields for LoginResult."

    authenticated: Literal[True]
    already_authenticated: bool
    password_saved: NotRequired[Literal[False]]


class MailDownload(TypedDict):
    "JSON response fields for MailDownload."

    id: str
    part_id: str | None
    saved_to: str
    bytes: int
    sha256: str


class AnswerOption(TypedDict):
    "JSON response fields for AnswerOption."

    value: str
    label: str
    selected: bool


class QuestionField(TypedDict):
    "JSON response fields for QuestionField."

    name: str
    type: str
    value: str
    label: str
    checked: bool
    required: bool
    maxlength: NotRequired[int]
    multiple: NotRequired[bool]
    options: NotRequired[list[AnswerOption]]


class QuestionData(TypedDict):
    "JSON response fields for QuestionData."

    id: str | None
    number: str | None
    title: str
    text: str
    fields: list[QuestionField]
    images: list[QuestionDataImagesItem]
    links: list[Link]


class QuestionDataImagesItem(TypedDict):
    "JSON response fields for QuestionDataImagesItem."

    url: str
    alt: str


class AttemptView(TypedDict):
    "JSON response fields for AttemptView."

    state: Literal["unavailable", "ready", "active", "submitted"]
    source_url: str
    title: str
    text: str
    questions: list[QuestionData]
    question_count_on_page: int
    total_pages: int | None
    single_page_supported: bool
    submission_confirmed: bool
    receipt: str | None
    pending_action: NotRequired[str | None]
    from_local_capture: NotRequired[bool]
    action: NotRequired[Literal["start", "save", "submit"]]
