"""Generate JSON-compatible Python types from the versioned response schemas.

Run from any directory; --check verifies the generated AST without requiring a
particular formatter version. Inline objects receive deterministic public names.
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(schemas):
    definitions = {}

    def kind(schema, name):
        if "$ref" in schema:
            return schema["$ref"].rsplit("/", 1)[1]
        if "const" in schema:
            return "Literal[" + repr(schema["const"]) + "]"
        if "enum" in schema:
            values = schema["enum"]
            non_null = [v for v in values if v is not None]
            value = "Literal[" + ", ".join(repr(v) for v in non_null) + "]" if non_null else "None"
            return value + (" | None" if None in values and non_null else "")
        types = schema.get("type")
        if isinstance(types, list):
            return " | ".join(kind({**schema, "type": t}, name) for t in types)
        if types == "array":
            return "list[" + kind(schema["items"], name + "Item") + "]"
        if types == "object":
            if "properties" not in schema:
                extra = schema.get("additionalProperties")
                return (
                    "dict[str, "
                    + (kind(extra, name + "Value") if isinstance(extra, dict) else "JSONValue")
                    + "]"
                )
            if name not in definitions:
                definitions[name] = None
                required = schema.get("required", [])
                fields = []
                for field, value in schema["properties"].items():
                    nested = name + "".join(w.title() for w in field.split("_"))
                    annotation = kind(value, nested)
                    if field not in required:
                        annotation = "NotRequired[" + annotation + "]"
                    fields.append(f"    {field}: {annotation}")
                description = schema.get("description", "JSON response fields for " + name + ".")
                definitions[name] = (
                    f"class {name}(TypedDict):\n    {description!r}\n\n"
                    + "\n".join(fields or ["    pass"])
                )
            return name
        primitives = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "null": "None",
        }
        if types not in primitives:
            raise ValueError(f"Unsupported schema for {name}: {schema!r}")
        return primitives[types]

    for name, schema in schemas.items():
        value = kind(schema, name)
        if name not in definitions:
            definitions[name] = f"{name}: TypeAlias = {value}"
    header = '''"""Public JSON-compatible return types. Generated by tools/generate_models.py.

These are ordinary dicts/lists at runtime, with TypedDict keys for autocomplete
and static checking. Optional keys use NotRequired; explicit null uses None.
They are type declarations, not a runtime validation or deserialization layer.
"""

from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict, Union

JSONValue: TypeAlias = Union[None, bool, int, float, str, list["JSONValue"], dict[str, "JSONValue"]]

'''
    return header + "\n\n\n".join(definitions.values()) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schemas = json.loads((ROOT / "docs/openapi.json").read_text())["components"]["schemas"]
    source = generate(schemas)
    target = ROOT / "src/ismu/models.py"
    if args.check:
        if not target.exists() or ast.dump(ast.parse(target.read_text())) != ast.dump(
            ast.parse(source)
        ):
            raise SystemExit("models.py is stale; run python tools/generate_models.py")
    else:
        target.write_text(source)


if __name__ == "__main__":
    main()
